Move normalization logic in a trait
GuilhemN/symfony pull request #2
Opened 2017-03-21 11:21 UTC by soyuka

| Q             | A
| ------------- | ---
| Branch?       | master / 2.7, 2.8, 3.1 or 3.2 
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Tests pass?   | yes/no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

2017-03-21 11:25 UTC, soyuka commented
I'm not sure where we could put these but I cleaned up the `CacheWarmer` and the `CompilerPass`, lmk if you want me to add them to this pull request!

2017-03-21 17:42 UTC, GuilhemN requested changes
I'm not sure this is worth it, it removes the max depth support and I don't think we should provide a trait for custom normalizers.

2017-03-21 17:42 UTC, GuilhemN commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function isAllowedAttribute($property, $attributeGroups, &$context) {
why the reference?

2017-03-21 17:42 UTC, GuilhemN commented on src/Symfony/Component/Serializer/Dumper/NormalizerDumper.php
> -                \$subContext = \$context;
I forgot to use it, but it should not be removed, it should be passed to the `normalize` call.

2017-03-21 17:42 UTC, GuilhemN commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function getValue($value, $property, $format, &$context) {
I'm not sure this should be shared, it will probably change soon if we use the PropertyInfo component.

2017-03-21 22:07 UTC, soyuka commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function isAllowedAttribute($property, $attributeGroups, &$context) {
Really no idea, I just like references but there's not point here I'll remove it.

2017-03-21 22:11 UTC, soyuka commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function getValue($value, $property, $format, &$context) {
Exactly, might be changed in this trait to avoid changing the code in the `<<<EOL`  thing.

2017-03-21 22:19 UTC, soyuka commented
How do we remove MaxDepth support?
I'll get into this a bit more just need to finalize some things for testing. I really think that the trait can help with maintenance and adding features.

By the way, I'm currently using:
- a cache warmer for the NormalizerDumper
- a Compiler Pass to dynamically add the normalizer service Definitions

What would you use in symfony to get a list of classes that would be dumped? A new configuration parameter? 

I'm also investigating a proper way to customize the dumped normalizer (jsonld support for example), without too much changes in the base serializer.

2017-03-22 11:36 UTC, GuilhemN commented
> How do we remove MaxDepth support?

We don't want to remove its support, every feature supported by the `ObjectNormalizer` should be supported by the dumped normalizers imo.

> What would you use in symfony to get a list of classes that would be dumped? A new configuration parameter?

Yes I think it's the best option.

> I'm also investigating a proper way to customize the dumped normalizer (jsonld support for example), without too much changes in the base serializer.

If the user wants something very specific, imo he should just create his own normalizer.

2017-03-22 11:41 UTC, GuilhemN commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function getValue($value, $property, $format, &$context) {
This won't be possible without losing performance as using the PropertyInfo component at runtime is expensive.

2017-03-22 13:14 UTC, soyuka commented
> We don't want to remove its support, every feature supported by the ObjectNormalizer should be supported by the dumped normalizers imo.

Indeed we should, I thought I kept the MaxDepth support here, this is why I didn't understood the comment. Needs some tests ofc.

> If the user wants something more specific, imo he should just create his own normalizer.

I mean if you still want to use dumped normalizers and use alternative features there are some ways to make those extendable. I've built a prototype that uses a `NormalizerDecorators` concept to add metadata (for example with JsonLd). Basically it calls a `decorate` method at the end of the normalization and adds an optional dependency to tagged services. Those tagged services are implementing this interface:

```php
interface NormalizerDecoratorInterface
{
    public function decorate($object, array $data, $format = null, array $context = []);
    public function supportsDecoration($object, $format = null, array $context = []);
}
```

@dunglas talked about some other ways to implement this:

- Use IoC (injected the generated normalizer in a new normalizer), would require a refactor of the serializer though
- Use extends (would also require a refactor of the serializer) where the custom would extend generated ones?
- Use a decorator system like above (does not need any modifications to the serializer)

Anyway, this is way out of scope for now!

If you're still convinced there's no point in adding a Trait for shared code that's no big deal. If you want me to update the code, let me know ;).
Note that it is also easier to debug with the Trait because the same method is called from all the normalizers, meaning that you don't need to dump everything when you want to test you just have to change things in the Trait.

2017-03-22 13:16 UTC, soyuka commented on src/Symfony/Component/Serializer/Normalizer/NormalizerDumperTrait.php
> +    private function getValue($value, $property, $format, &$context) {
Okay get it, indeed this should not be shared.

2017-03-22 14:01 UTC, GuilhemN commented
> Use IoC (injected the generated normalizer in a new normalizer), would require a refactor of the serializer though

This is what I prefer. Why would it require to update the serializer?
People could just do something like:
```yml
services:
    App\Normalizer\JsonLdNormalizer:
        decorates: normalizers.App\Model\Foo # hypothetic name
        arguments: [ "@App\Normalizer\JsonLdNormalizer.inner" ]
```
```php
class JsonLdNormalizer implements NormalizerInterface
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        // ...
    }

    public function normalize($object, $format = null, array $context = array())
    {
        $output = $this->decorated->normalize($object, $format, $context);

        return $output;
    }

    // ...
}
```

> If you're still convinced there's no point in adding a Trait for shared code that's no big deal. If you want me to update the code, let me know ;).

I personally don't see the point, maybe the others would like it though, you'll still be able to open an issue/a PR on `symfony` repository later if the PR is merged to see what people think about it.

> Note that it is also easier to debug with the Trait because the same method is called from all the normalizers, meaning that you don't need to dump everything when you want to test you just have to change things in the Trait.

You can also update the dumper :)

2017-03-22 14:09 UTC, GuilhemN commented
> Indeed we should, I thought I kept the MaxDepth support here, this is why I didn't understood the comment. Needs some tests ofc.

It is normally covered, didn't you get an error while running the tests?

2017-03-22 14:18 UTC, soyuka commented
> You can also update the dumper :)

Ofc, but it's harder to code in a string then in a real class :p.

About injecting the generated normalizer there is some drawback though. Because we generate a normalizer per class (I've 91 normalizers now), we would need as much JsonLdNormalizers as we have generated normalizers? I'd need to go deeper in the serializer to see if this requires a change but I think it has to do with `getNormalizer` and those `parent::normalize` things everywhere.

If you do decorate the other way arround, you can define one decorator that's being used for every generated normalizer. 

> It is normally covered, didn't you get an error while running the tests?

Didn't ran the tests, but yes this should still work. My bad.

> I personally don't see the point, maybe the others would like it though, you'll still be able to open an issue/a PR on symfony repository later if the PR is merged to see what people think about it.

Fine by me!

2017-03-22 14:21 UTC, GuilhemN commented
> About injecting the generated normalizer there is some drawback though. Because we generate a normalizer per class (I've 91 normalizers now), we would need as much JsonLdNormalizers as we have generated normalizers? I'd need to go deeper in the serializer to see if this requires a change but I think it has to do with getNormalizer and those parent::normalize things everywhere.

We could inject all the generated normalizers in a `ChainNormalizer`. Then by decorating this normalizer you would decorate all of them.

2017-03-22 14:31 UTC, soyuka commented
Great idea! I'll definitely try this to see if it require changes to the serializer! Thanks!

2017-03-22 14:32 UTC, soyuka commented
Closing, as said above I'll add a PR to symfony if the PR gets merged for the trait (if I still see any point adding it after our discussion) ;).

2017-03-22 14:32 UTC, closed without merging